### ISSUE TITLE
Simplified installation on Windows 10

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik#281]
## Overview
In order to simplify the installation of the ARTIK IDE we will create an installer and an [Electron client](http://electron.atom.io/). The Electron client will use the same source code as the current browser IDE, but wrap it in a desktop client that allows a single icon click to start the ARTIK IDE. For this phase the installer and Electron client will only be designed to work with a locally installed ARTIK IDE, but future efforts could allow this client to connect to a remote ARTIK server - such as one hosted at `ide.artik.cloud`.

The installer will take care of laying down all ARTIK IDE dependencies including the Electron client, the ARTIK IDE container images and ARTIK stack image. The installer will check for the existence of Docker and, if necessary, install it. It will unpack the ARTIK IDE images and start the ARTIK server (the ARTIK IDE server will be executed in an "always-run" mode in Docker - this will allow ARTIK IDE startup time to be very fast and give users a highly responsive experience). Finally, it will create a desktop icon / shortcut for the ARTIK IDE.

When the ARTIK IDE desktop icon is clicked, the Electron client will start on the users desktop and allow the user to configure proxies and connect to the locally running ARTIK server. Checks will be performed to:
- Ensure that Docker is running
- Ensure that the ARTIK IDE server is running
- Ensure that there is connectivity from the container to the internet

If any of the checks fail there will be notifications and, in some cases, configuration options presented to the user to allow them to address any issues.

When the Electron client is stopped the ARTIK server will continue to run and the user will be presented with the option of stopping running workspaces or leaving them run.

Specifications for this are captured in an [ARTIK Installer and Electron Client specification](https://docs.google.com/document/d/1izSvR2iQSxHiYLSQqTwPsUT_3DOLJHelEPDySLmazYQ/edit?usp=sharing).

There are companion epics for the same work on [Mac OS](https://github.com/codenvy/artik-ide/issues/282).

### Installer  #292
- [x] Installer: Install package (.exe) containing Docker, Electron client, Docker images for ARTIK server, ARTIK stack and utilities (https://github.com/codenvy/artik-ide/issues/264).
- [x] Installer: License display and user acceptance panel.
- [ ] Installer: Electron client install location panel - including testing if Electron can be run in a directory with spaces and, if not, trapping for that issue when selecting paths.
- [x] Installer: Docker install and version check for Docker 1.12.5+.
- [x] Installer: `docker load` for TAR'ed images.
- [x] Installer: ARTIK Server containers set to auto-restart in Docker.
- [x] Installer: Create a desktop icon for "Samsung ARTIK IDE" (the Electron client)
- [ ] Installer: Starts Electron client

### Electron Client
- [x] Electron: The electron packaging should have the ARTIK IDE icon, provide minimize / maximize, and also have an icon that appears in the system tray when minified.
- [x] Electron: The client will perform checks each time it is loaded:
  - Check for ARTIK Server availability.
  - Check for internet connectivity.
  - Check for Docker availability.
- [x] Electron: Completed start page with checks and handling of ARTIK Server and connectivity failures as well as allowing configuration of ARTIK data directory and Docker proxy settings.
- [x] Electron: Proxy settings pulled from Docker.
- [x] Electron: Connects to local ARTIK Server.

### Docs
- [ ] Docs: Docs on operating installer including an installation guide and a quick start guide.

**Comment by vparfonov** [comment]
@bmicklea i am not sure that docker load for TAR'ed images must do installer, i thin will be better if Electron client  will do it on first run

**Comment by bmicklea** [comment]
What's the problem with sound Docker load during installer run?

Ideally the ARTIK server will be running when the electron client is first
started. We could add definition of data path to the installer.
