### ISSUE TITLE
Simplified installation on Mac OS

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik#282]
## Overview
In order to simplify the installation of the ARTIK IDE we will create an installer and an [Electron client](http://electron.atom.io/). The Electron client will use the same source code as the current browser IDE, but wrap it in a desktop client that allows a single icon click to start the ARTIK IDE. For this phase the installer and Electron client will only be designed to work with a locally installed ARTIK IDE, but future efforts could allow this client to connect to a remote ARTIK server - such as one hosted at `ide.artik.cloud`.

The installer will take care of laying down all ARTIK IDE dependencies including the Electron client, the ARTIK IDE container images and ARTIK stack image. The installer will check for the existence of Docker and, if necessary, install it. It will unpack the ARTIK IDE images and start the ARTIK server (the ARTIK IDE server will be executed in an "always-run" mode in Docker - this will allow ARTIK IDE startup time to be very fast and give users a highly responsive experience). Finally, it will create a desktop icon / shortcut for the ARTIK IDE.

When the ARTIK IDE desktop icon is clicked, the Electron client will start on the users desktop and allow the user to configure proxies and connect to the locally running ARTIK server. Checks will be performed to:
- Ensure that Docker is running
- Ensure that the ARTIK IDE server is running
- Ensure that there is connectivity from the container to the internet

If any of the checks fail there will be notifications and, in some cases, configuration options presented to the user to allow them to address any issues.

When the Electron client is stopped the ARTIK server will continue to run and the user will be presented with the option of stopping running workspaces or leaving them run.

Specifications for this are captured in an [ARTIK Installer and Electron Client specification](https://docs.google.com/document/d/1izSvR2iQSxHiYLSQqTwPsUT_3DOLJHelEPDySLmazYQ/edit?usp=sharing).

There are companion epics for the same work on [Windows 10](https://github.com/codenvy/artik-ide/issues/281).

## Issues
- [x] Installer: Investigate installation procedure on Mac OS #290
- [ ] Installer: Install package (.dmg) containing Docker, Electron client, Docker images for ARTIK server, ARTIK stack and utilities (https://github.com/codenvy/artik-ide/issues/264).
- [ ] Installer: License display and user acceptance panel.
- [ ] Installer: Electron client install location panel.
- [ ] Installer: Docker install and version check for Docker 1.12.5+.
- [ ] Installer: `docker load` for TAR'ed images.
- [ ] Installer: ARTIK Server containers set to auto-restart in Docker.
- [ ] Installer: Create a application icon for "Samsung ARTIK IDE" (the Electron client) and offers to put it in the Dock.
- [ ] Installer: Starts Electron client
- [ ] Electron: The electron packaging should have the ARTIK IDE icon, provide minimize / maximize, and also have an icon that appears in the system tray when minified.
- [ ] Electron: The client will perform checks each time it is loaded:
  - Check for ARTIK Server availability.
  - Check for internet connectivity.
  - Check for Docker availability.
- [ ] Electron: Completed start page with checks and handling of ARTIK Server and connectivity failures as well as allowing configuration of ARTIK data directory and Docker proxy settings.
- [ ] Electron: Proxy settings propagated to Docker.
- [ ] Electron: Connects to local ARTIK Server.
- [ ] Docs: Docs on operating installer including an installation guide and a quick start guide.

**Comment by vparfonov** [comment]
@benoitf  Florent, I heard that you have some experience in this field, so may be you could advise where we can start from or what tool can be applied here. Thanks

**Comment by TylerJewell** [comment]
@vparfonov - for which parts?  It's a huge specification, so be more specific.

**Comment by vparfonov** [comment]
Well, we have a specific use case here, we're in a situation when we need to figure out if docker is installed and install it if needed. So what we probably must have an installer (seems like dmg format can't be applied here) that will run some script and start installation of another package (with docker) and then install our application.

**Comment by benoitf** [comment]
@vparfonov AFAIK .pkg is installer format for macOs, you may build it with https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pkgbuild.1.html
we had in the past an installer https://github.com/codenvy/che-installer/tree/3.x/eclipse-che-installer-osx

but I would say dmg file is still the more common for mac ppl. Also with Electron we can have this kind of dmg file support. And we should be able to check if docker is installed or not inside the electron package.


I found https://github.com/khornberg/docker-indicator which communicate with docker
it uses library https://www.npmjs.com/package/dockerode (that can connect to docker socket)

**Comment by vparfonov** [comment]
@benoitf  thanks for your answer. But i think check if docker is installed or not inside the electron package will too late. We should check this during installation like we do for Windows 10. 
We will try docker-indicator
