### ISSUE TITLE
Create electron client packaging of Artik IDE for Windows (exe), Mac (dmg), and Linux (zip / tgz)

### ISSUE THREAD

**Issue by vparfonov** [codenvy/artik#287]
- [ ] Electron: The electron packaging should have the ARTIK IDE icon, provide minimize / maximize, and also have an icon that appears in the system tray when minified.  #291
- [ ] Electron: The client will perform checks each time it is loaded:
  - Check for ARTIK Server availability.
  - Check for internet connectivity.
  - Check for Docker availability.
- [ ] Electron: Completed start page with checks and handling of ARTIK Server and connectivity failures as well as allowing configuration of ARTIK data directory and Docker proxy settings.
- [ ] Electron: Proxy settings propagated to Docker.
- [ ] Electron: Connects to local ARTIK Server.  #291
