### ISSUE TITLE
Simplified Installation on Windows 7/8

### ISSUE THREAD

**Issue by bmicklea** [codenvy/artik#358]
## Overview
In order to simplify the installation of the ARTIK IDE we will create an installer and an [Electron client](http://electron.atom.io/). The Electron client will use the same source code as the current browser IDE, but wrap it in a desktop client that allows a single icon click to start the ARTIK IDE. For this phase the installer and Electron client will only be designed to work with a locally installed ARTIK IDE, but future efforts could allow this client to connect to a remote ARTIK server - such as one hosted at `ide.artik.cloud`.

For Win 7/8 the installer will need to deal with Docker Toolbox, VirtualBox and ARTIK IDE - it should install each if they aren't found on the system and upgrade them if they are found but not at the right version.

As with the Windows 10 installer this one will create shortcuts and ensure that Docker sharing and proxy (if required) are properly installed.

The Electron client will likely require very few changes.

### Installer
- [ ] Installer: Install package (.exe) containing Docker Toolbox, VirtualBox, Electron client, Docker images for ARTIK server, ARTIK stack and utilities.
- [ ] Installer: License display and user acceptance panel.
- [ ] Installer: Electron client install location panel - including testing if Electron can be run in a directory with spaces and, if not, trapping for that issue when selecting paths.
- [ ] Installer: Check that Windows virtualization is turned on.
- [ ] Installer: Check for VirtualBox install and version.
- [ ] Installer: Docker Toolbox install and version check.
- [ ] Installer: `docker load` for TAR'ed images.
- [ ] Installer: ARTIK Server containers set to auto-restart in Docker.
- [ ] Installer: Create a desktop icon for "Samsung ARTIK IDE" (the Electron client)
- [ ] Installer: Starts Electron client

### Electron Client
- [ ] Electron: The electron packaging should have the ARTIK IDE icon, provide minimize / maximize, and also have an icon that appears in the system tray when minified.
- [ ] Electron: The client will perform checks each time it is loaded:
  - Check for ARTIK Server availability.
  - Check for internet connectivity.
  - Check for Docker + VirtualBox availability.
- [ ] Electron: Completed start page with checks and handling of ARTIK Server and connectivity failures as well as allowing configuration of ARTIK data directory and Docker proxy settings.
- [ ] Electron: Proxy settings pulled from Docker.
- [ ] Electron: Connects to local ARTIK Server.

### Docs
- [ ] Docs: Docs on operating installer including an installation guide and a quick start guide.
